export const VALIDATION_RETRY_QUERIES: { pattern: RegExp; retryQuery: string }[] = [
  { pattern: /specific stock/i, retryQuery: 'AMD stock' },
  { pattern: /favorite video game/i, retryQuery: 'cyberpunk 2077' },
  { pattern: /gaming time/i, retryQuery: 'cyberpunk 2077' },
  {
    pattern: /favorite movie|watch that movie|find that flick|lights?.camera|let.?s watch/i,
    retryQuery: 'Jurassic Park movie series',
  },
  {
    pattern: /next adventure|somewhere new to explore|explore a new spot/i,
    retryQuery: 'directions to las vegas',
  },
  { pattern: /your team|who won/i, retryQuery: 'Tampa Bay Lightning games' },
  { pattern: /your shopping list|shopping.*done.*faster/i, retryQuery: 'grocery list eggs' },
  { pattern: /your package|track package/i, retryQuery: 'track UPS package' },
  { pattern: /translate/i, retryQuery: 'translate amigo to english' },
  {
    pattern: /a flight to your perfect vacation|flight destination|perfect flight/i,
    retryQuery: 'flights to tokyo',
  },
  { pattern: /prepare for weather|weather/i, retryQuery: 'weather' },
  { pattern: /check symptoms/i, retryQuery: 'check symptoms for flu' },
  { pattern: /latest news/i, retryQuery: 'check latest news' },
  { pattern: /search lyrics|lyrics/i, retryQuery: 'lyrics to bohemian rhapsody' },
  { pattern: /up to date with election|election/i, retryQuery: 'US Elections' },
  { pattern: /find places to stay|hotel/i, retryQuery: 'hotels near me' },
  { pattern: /restaurant|tired to cook/i, retryQuery: "mcdonald's restaurant near me" },
  { pattern: /find houses|real estate/i, retryQuery: 'houses for sale near me' },
  { pattern: /how.?s the economy|economy/i, retryQuery: 'Nvidia stock' },
  { pattern: /expand your vocabulary/i, retryQuery: 'definition of curious' },
  { pattern: /quickly convert money|convert money/i, retryQuery: '5 usd to yen' },
  { pattern: /job|role opening/i, retryQuery: 'job openings at Amazon' },
  { pattern: /get creative/i, retryQuery: 'do it yourself crafts' },
  { pattern: /fresh up your routine/i, retryQuery: 'haircare products' },
  { pattern: /packing made easy/i, retryQuery: 'travel essentials packing list' },
  { pattern: /serengeti/i, retryQuery: 'Serengeti National Park' },
  { pattern: /for traveling/i, retryQuery: 'directions to las vegas' },
];

export const WARMUP_SEARCH_QUERIES: string[] = [
  'current time in tokyo',
  'calories in an avocado',
  'how tall is mount everest',
  'what year did the titanic sink',
  'fastest land animal',
  'how many planets in the solar system',
  'who painted the mona lisa',
  'capital of australia',
  'how to convert celsius to fahrenheit',
  'what is the speed of light',
  'largest ocean on earth',
  'how many bones in the human body',
  'who invented the telephone',
  'what language is spoken in brazil',
  'longest river in the world',
  'how many days in a leap year',
  'what is the currency of japan',
  'how far is the moon from earth',
  'who wrote hamlet',
  'what is the boiling point of water',
  'largest country by area',
  'how many teeth do adults have',
  'what is the capital of canada',
  'who discovered penicillin',
  'how many minutes in a day',
  'what is the smallest planet',
  'who was the first us president',
  'how many continents are there',
  'what is the chemical symbol for gold',
  'how deep is the mariana trench',
];

export const PC_SEARCH_QUERIES: string[] = [
  'weather forecast today',
  'best hiking trails near me',
  'how to make sourdough bread',
  'latest space exploration news',
  'classic movies to watch',
  'how to learn guitar for beginners',
  'best coffee shops in the world',
  'top national parks in the US',
  'history of the Roman Empire',
  'how does a black hole form',
  'easy weeknight dinner recipes',
  'best board games for adults',
  'how to start a vegetable garden',
  'most popular programming languages 2024',
  'how to improve sleep quality',
  'famous paintings and their artists',
  'beginner yoga poses for flexibility',
  'how to change a car tire',
  'best sci-fi books of all time',
  'how to make homemade pasta',
  'tips for learning a new language',
  'how do vaccines work',
  'best documentaries on Netflix',
  'how to save money on groceries',
  'world record longest running TV show',
  'how to tie a bowline knot',
  'what causes the northern lights',
  'best electric vehicles 2024',
  'how to write a cover letter',
  'history of the Great Wall of China',
  'how to make cold brew coffee',
  'best productivity apps for students',
  'what is quantum computing',
  'how to train for a 5k run',
  'famous unsolved mysteries in history',
  'best beaches in the world',
  'how to invest in index funds',
  'how does the immune system work',
  'best cooking shows on streaming',
  'how to grow indoor plants',
  'what is the Fermi paradox',
  'best mystery novels of all time',
  'how to make kombucha at home',
  'history of ancient Egypt',
  'how to speed read effectively',
  'best mechanical keyboards 2024',
  'how do solar panels work',
  'tips for better public speaking',
  'how to make homemade ice cream',
  'most visited museums in the world',
  'how to set up a home gym',
  'what causes earthquakes',
  'best podcasts for learning',
  'how to brew beer at home',
  'history of the internet',
  'how to meditate for beginners',
  'best travel destinations in Europe',
  'how do airplanes generate lift',
  'what is the gut microbiome',
  'best strategy games on PC',
  'how to start journaling',
  'history of jazz music',
  'how to build a standing desk',
  'what is CRISPR gene editing',
  'best ways to learn to cook',
  'how to pick a bike lock',
  'most extreme weather events on record',
  'how to make sushi at home',
  'best telescope for beginners',
  'what is dark matter',
  'how to reduce plastic waste',
  'best thriller movies of the decade',
  'how to learn chess openings',
  'history of the Olympics',
  'how to care for a succulent',
  'what causes ocean tides',
  'best noise canceling headphones 2024',
  'how to write a short story',
  'history of the printing press',
  'how to do a digital detox',
  // --- added batch ---
  // Weather & local
  '10 day weather forecast',
  'sunset time today',
  'sunrise time tomorrow',
  'weather radar near me',
  'humidity levels today',
  'UV index forecast',
  'air quality index near me',
  'pollen count today',
  'wind speed forecast',
  'chance of snow this week',
  // News & current events
  'NBA playoffs schedule',
  'gas prices near me',
  'stock market news today',
  'headlines this morning',
  'local news near me',
  'election results 2024',
  'sports scores today',
  'NFL standings current season',
  'world cup 2026 schedule',
  'top stories CNN',
  // How-to & DIY
  'how to fix a leaky faucet',
  'how to remove a stripped screw',
  'how to unclog a drain',
  'how to patch drywall',
  'how to hang pictures on a wall',
  'how to install a ceiling fan',
  'how to paint a room',
  'how to replace a light switch',
  'how to snake a drain',
  'how to reseed a lawn',
  'how to sharpen kitchen knives',
  'how to clean a cast iron skillet',
  'how to remove wine stains',
  'how to fold a fitted sheet',
  'how to sew a button',
  'how to iron a dress shirt',
  'how to descale a coffee maker',
  'how to clean an oven',
  'how to organize a garage',
  'how to get rid of fruit flies',
  // Food & recipes
  'chicken tikka masala recipe',
  'how long to boil eggs',
  'how to make guacamole',
  'best banana bread recipe',
  'how to make French toast',
  'beef stew recipe slow cooker',
  'how to make butter chicken',
  'easy pancake recipe from scratch',
  'how to roast a whole chicken',
  'best chili recipe',
  'how to make fried rice',
  'homemade pizza dough recipe',
  'how to make a smoothie bowl',
  'best mac and cheese recipe',
  'how to make cream of mushroom soup',
  'how to make beef tacos',
  'pesto pasta recipe',
  'how to make caramel from scratch',
  'baked salmon recipe',
  'how to make overnight oats',
  // Health & fitness
  'signs of vitamin D deficiency',
  'how many calories in a banana',
  'how many steps a day is healthy',
  'symptoms of high blood pressure',
  'how much water should I drink daily',
  'best stretches for lower back pain',
  'how to lower cholesterol naturally',
  'what does magnesium do for the body',
  'signs of dehydration',
  'how to reduce inflammation in the body',
  'best foods for gut health',
  'how to improve posture',
  'benefits of cold showers',
  'how many hours of sleep do adults need',
  'what is intermittent fasting',
  'how to build muscle fast',
  'best cardio exercises for weight loss',
  'how to stop snoring',
  'causes of chronic fatigue',
  'how to boost immune system naturally',
  // Tech & products
  'best budget laptop 2025',
  'iPhone vs Android which is better',
  'best wireless earbuds under 100',
  'how to speed up a slow computer',
  'best password managers',
  'how to set up a VPN',
  'what is the difference between RAM and ROM',
  'best antivirus software 2025',
  'how to back up your iPhone',
  'best smart home devices',
  'how to clear browser cache',
  'what is cloud computing explained simply',
  'best gaming monitors 2025',
  'how to extend laptop battery life',
  'best streaming devices for TV',
  'difference between 4K and 8K TV',
  'best robot vacuum 2025',
  'how to set up two factor authentication',
  'best free photo editing software',
  'how to block ads on Chrome',
  // Travel
  'cheap flights to Miami',
  'best time to visit Japan',
  'things to do in New York City',
  'how to get a US passport',
  'travel tips for first time flyers',
  'best travel insurance plans',
  'things to pack for a beach vacation',
  'safest countries to travel to',
  'best budget airlines in the US',
  'Airbnb vs hotel which is better',
  'things to do in Paris France',
  'best road trip routes in the US',
  'how to avoid jet lag',
  'best national parks to visit in summer',
  'travel adapter for Europe',
  'best cruises for families',
  'cheapest places to travel in 2025',
  'things to do in London England',
  'how to find cheap hotels',
  'best time to book flights',
  // Finance & money
  'how to file taxes online for free',
  'S&P 500 historical returns',
  'how to open a Roth IRA',
  'what is a good credit score',
  'how to improve credit score fast',
  'best high yield savings accounts',
  'how to budget for beginners',
  'difference between stocks and bonds',
  'what is compound interest',
  'how to pay off student loans faster',
  'best budgeting apps',
  'what is a 401k explained',
  'how to negotiate a salary',
  'what is the federal funds rate',
  'best cash back credit cards',
  'how to dispute a charge on credit card',
  'what is term life insurance',
  'how to start an emergency fund',
  'what is dollar cost averaging',
  'how much should I save for retirement',
  // Entertainment
  'new movies coming out this weekend',
  'top songs on Spotify this week',
  'best TV shows to binge watch 2025',
  'new albums released this month',
  'best stand up comedy specials on Netflix',
  'Marvel movies in chronological order',
  'best video games of 2025',
  'upcoming concerts near me',
  'best anime to watch right now',
  'most popular YouTube channels',
  'Taylor Swift tour dates 2025',
  'best horror movies of all time',
  'Oscar winners 2025',
  'best comedy movies on Netflix',
  'classic video games to play',
  'best animated movies for adults',
  'most anticipated games of 2025',
  'best true crime podcasts',
  'new book releases this month',
  'Spotify wrapped how to see',
  // General knowledge & trivia
  'how fast does light travel',
  'population of Texas',
  'how deep is the Mariana Trench',
  'what is the capital of Australia',
  'how old is the universe',
  'how many bones are in the human body',
  'what causes rainbows',
  'why is the sky blue',
  'how long does it take to get to Mars',
  'what is the speed of sound',
  'who invented the telephone',
  'how big is the Amazon rainforest',
  'what is the largest country by area',
  'how tall is the Eiffel Tower',
  'what language is spoken in Brazil',
  'how many countries are in the world',
  'what is the deepest lake in the world',
  'what is the longest river in the world',
  'how hot is the surface of the sun',
  'how long does a human hair grow per month',
  // Shopping & product research
  'best running shoes for flat feet',
  'dishwasher reviews 2025',
  'best mattress for back pain',
  'most durable work boots',
  'best standing desk under 500',
  'top rated air purifiers',
  'best instant pot recipes',
  'carry on luggage size requirements',
  'best sunscreen for sensitive skin',
  'most comfortable office chair',
  'best coffee grinder for home',
  'top rated blenders 2025',
  'best winter coats for men',
  'best skincare routine for beginners',
  'most reliable used cars to buy',
  'best dog food for large breeds',
  'top rated baby monitors',
  'best cordless drill 2025',
  'best outdoor grill under 300',
  'top rated humidifiers for bedroom',
  // Pets & home
  'best dry dog food brands',
  'how to litter train a kitten',
  'why does my dog eat grass',
  'how often should you bathe a dog',
  'best aquarium fish for beginners',
  'how to get rid of ants in the house',
  'best indoor air plants',
  'how to keep cats off counters',
  'signs a dog has fleas',
  'how to stop a dog from barking',
  // Automotive
  'how often to change oil in a car',
  'what does the check engine light mean',
  'how to jump start a dead battery',
  'best tire brands 2025',
  'how to check tire pressure',
  'symptoms of a bad alternator',
  'how to clean car interior',
  'what is synthetic motor oil',
  'best dash cam under 100',
  'how long do car brakes last',
  // Education & career
  'how to write a resume with no experience',
  'best free online courses',
  'how to prepare for a job interview',
  'highest paying careers without a degree',
  'how to ask for a raise',
  'SAT prep tips',
  'what GPA do you need for medical school',
  'best certifications for IT professionals',
  'how to get a real estate license',
  'difference between MBA and MBA online',
  // Relationships & lifestyle
  'first date ideas near me',
  'how to apologize sincerely',
  'how to make friends as an adult',
  'signs of a healthy relationship',
  'how to stop overthinking',
  'how to deal with difficult coworkers',
  'tips for work life balance',
  'how to be more productive at work',
  'morning routine ideas',
  'how to declutter your home',
  // Random searches people actually do
  'what time does Costco close',
  'is the post office open on Saturday',
  'how much does a car wash cost',
  'what year did World War 2 end',
  'how to say thank you in Spanish',
  'miles from New York to Los Angeles',
  'how many ounces in a pound',
  'what does RSVP stand for',
  'how many cups in a gallon',
  'time zones in the United States',
];
