export const PC_SEARCH_QUERIES = [
  'weather forecast today',
  'best hiking trails near me',
  'how to make sourdough bread',
  'latest space exploration news',
  'classic movies to watch',
  'how to learn guitar for beginners',
  'best coffee shops in the world',
  'top national parks in the US',
  'history of the Roman Empire',
  'how does a black hole form',
  'easy weeknight dinner recipes',
  'best board games for adults',
  'how to start a vegetable garden',
  'most popular programming languages 2024',
  'how to improve sleep quality',
  'famous paintings and their artists',
  'beginner yoga poses for flexibility',
  'how to change a car tire',
  'best sci-fi books of all time',
  'how to make homemade pasta',
  'tips for learning a new language',
  'how do vaccines work',
  'best documentaries on Netflix',
  'how to save money on groceries',
  'world record longest running TV show',
  'how to tie a bowline knot',
  'what causes the northern lights',
  'best electric vehicles 2024',
  'how to write a cover letter',
  'history of the Great Wall of China',
  'how to make cold brew coffee',
  'best productivity apps for students',
  'what is quantum computing',
  'how to train for a 5k run',
  'famous unsolved mysteries in history',
  'best beaches in the world',
  'how to invest in index funds',
  'how does the immune system work',
  'best cooking shows on streaming',
  'how to grow indoor plants',
  'what is the Fermi paradox',
  'best mystery novels of all time',
  'how to make kombucha at home',
  'history of ancient Egypt',
  'how to speed read effectively',
  'best mechanical keyboards 2024',
  'how do solar panels work',
  'tips for better public speaking',
  'how to make homemade ice cream',
  'most visited museums in the world',
  'how to set up a home gym',
  'what causes earthquakes',
  'best podcasts for learning',
  'how to brew beer at home',
  'history of the internet',
  'how to meditate for beginners',
  'best travel destinations in Europe',
  'how do airplanes generate lift',
  'what is the gut microbiome',
  'best strategy games on PC',
  'how to start journaling',
  'history of jazz music',
  'how to build a standing desk',
  'what is CRISPR gene editing',
  'best ways to learn to cook',
  'how to pick a bike lock',
  'most extreme weather events on record',
  'how to make sushi at home',
  'best telescope for beginners',
  'what is dark matter',
  'how to reduce plastic waste',
  'best thriller movies of the decade',
  'how to learn chess openings',
  'history of the Olympics',
  'how to care for a succulent',
  'what causes ocean tides',
  'best noise canceling headphones 2024',
  'how to write a short story',
  'history of the printing press',
  'how to do a digital detox',
];
